######################################################################
# Automatically generated by qmake (2.01a) Sun Aug 28 11:13:57 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .


QMAKE_CXXFLAGS += -std=c++11


# Input
HEADERS += main_window.h alphaflame.h
SOURCES += main.cpp main_window.cpp alphaflame.cpp
