######################################################################
# Automatically generated by qmake (2.01a) Sun Aug 28 11:13:57 2016
######################################################################

TEMPLATE = app
TARGET = AF_Filter
DEPENDPATH += .
INCLUDEPATH += .

QT += core widgets gui
QMAKE_CXXFLAGS += -std=c++11
RESOURCES += qresource.qrc

# Input
HEADERS += main_window.h alphaflame.h
SOURCES += main.cpp main_window.cpp alphaflame.cpp
