#!/bin/sh

#cp -R /usr/local/opt/qt/lib/QtCore.framework AF_Filter.app/Contents/Frameworks
#cp -R /usr/local/opt/qt/lib/QtGui.framework AF_Filter.app/Contents/Frameworks

install_name_tool -id @executable_path/../Frameworks/QtGui.framework/Versions/4/QtGui AF_Filter.app/Contents/Frameworks/QtGui.framework/Versions/4/QtGui

install_name_tool -id @executable_path/../Frameworks/QtCore.framework/Versions/4/QtCore AF_Filter.app/Contents/Frameworks/QtCore.framework/Versions/4/QtCore

install_name_tool -change /Volumes/LostDrive-6/Users/jared/usr.local/local/opt/qt/lib/QtCore.framework/Versions/4/QtCore @executable_path/../Frameworks/QtCore.framework/Versions/4/QtCore AF_Filter.app/Contents/Frameworks/QtGui.framework/Versions/4/QtGui

install_name_tool -change /Volumes/LostDrive-6/Users/jared/usr.local/local/opt/qt/lib/QtGui.framework/Versions/4/QtGui @executable_path/../Frameworks/QtGui.framework/Versions/4/QtGui AF_Filter.app/Contents/MacOS/AF_Filter

install_name_tool -change /Volumes/LostDrive-6/Users/jared/usr.local/local/opt/qt/lib/QtCore.framework/Versions/4/QtCore @executable_path/../Frameworks/QtCore.framework/Versions/4/QtCore AF_Filter.app/Contents/MacOS/AF_Filter

install_name_tool -change /Volumes/LostDrive-6/Users/jared/usr.local/local/Cellar/qt/4.8.7_2/lib/QtCore.framework/Versions/4/QtCore @executable_path/../Frameworks/QtCore.framework/Versions/4/QtCore AF_Filter.app/Contents/Frameworks/QtGui.framework/Versions/4/QtGui

install_name_tool -change /Volumes/LostDrive-6/Users/jared/usr.local/local/opt/qt/lib/QtCore.framework/Versions/4/QtCore @executable_path/../Frameworks/QtCore.framework/Versions/4/QtCore AF_Filter.app/Contents/Frameworks/QtCore.framework/Versions/4/QtCore
